# HTTP(S) proxy server port
port: 7890

# SOCKS5 proxy server port
socks-port: 7891

# Transparent proxy server port for Linux and macOS (TCP and TProxy UDP redirection)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS4(A)/SOCKS5 proxy server share one port
# mixed-port: 7890

# Authentication for local SOCKS5/HTTP(S) proxy server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections from other LAN IP addresses
# allow-lan: false

# Only valid when `allow-lan` is `true`
# '*': Bind all IP addresses
# 192.168.122.11: Bind single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": Bind single IPv6 address
# bind-address: '*'

# Clash routing mode
# rule: Rule-based packet routing
# global: All packets will be forwarded to a single node
# direct: Directly forward packets to the Internet
mode: rule

# By default, Clash prints logs to STDOUT
# Log level: info / warning / error / debug / silent
log-level: info

# When set to false, the resolver will not resolve hostnames to IPv6 addresses
# ipv6: false

# RESTful Web API listening address
external-controller: 127.0.0.1:9090

# Relative path to the configuration directory or absolute path to the static Web resource directory. Clash core will serve at
# `http://{{external-controller}}/ui`
# external-ui: folder

# RESTful API secret (Optional)
# Authenticate by specifying HTTP header `Authorization: Bearer ${secret}`
# If RESTful API listens on 0.0.0.0, be sure to set a secret key.
# secret: ""

# Outbound interface name
# interface-name: en0

# fwmark (Only valid on Linux)
# routing-mark: 6666

# Static hosts for DNS server and connection establishment (like /etc/hosts).
#
# Support wildcard hostnames (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals .foo.com and foo.com
# hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

# profile:
  # Store `select` manual results in $HOME/.config/clash/.cache
  # Set to false if this behavior is not needed
  # When two different configurations have groups with the same name, the selected value will be shared
  # store-selected: true

  # Persist fakeip
  # store-fake-ip: false

# DNS service settings
# This section is optional. When not present, DNS service will be disabled.
dns:
  enable: false
  listen: 0.0.0.0:53
  # ipv6: false # When false, AAAA query response will be empty

  # These nameservers are used to resolve the following DNS nameserver hostnames.
  # Specifying IP addresses only
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  # enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP address pool CIDR
  # use-hosts: true # Look up hosts and return IP records

  # search-domains: [local] # Search domains for A/AAAA records

  # Hostnames in this list will not be resolved using Fake IP
  # i.e., requests to these domains will always be responded to with their real IP addresses
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS queries are sent directly to nameservers without proxy
  # Clash uses the first received response as the DNS query result.
  nameserver:
    - 114.114.114.114 # Default
    - 8.8.8.8 # Default
    - tls://dns.rubyfish.cn:853 # DNS over TLS
    - https://1.1.1.1/dns-query # DNS over HTTPS
    - dhcp://en0 # DNS from DHCP
    # - '8.8.8.8#en0'

  # When 'fallback' exists, the DNS server will send concurrent requests to servers in this section
  # and servers in 'nameservers'
  # When GEOIP country is not 'CN', the response from fallback servers will be used
  # fallback:
  #   - tcp://1.1.1.1
  #   - 'tcp://1.1.1.1#en0'

  # If the IP address resolved using 'nameservers' is in the subnet specified below,
  # they are considered invalid, and results from 'fallback' servers are used.
  #
  # When 'fallback-filter.geoip' is true and the IP address's GEOIP is 'CN',
  # the IP address resolved by 'nameservers' servers will be used.
  #
  # If 'fallback-filter.geoip' is false, and does not match 'fallback-filter.ipcidr',
  # the results from 'nameservers' servers are always used
  #
  # This is a measure against DNS pollution attacks.
  # fallback-filter:
  #   geoip: true
  #   geoip-code: CN
  #   ipcidr:
  #     - 240.0.0.0/4
  #   domain:
  #     - '+.google.com'
  #     - '+.facebook.com'
  #     - '+.youtube.com'

  # Lookup domains via specific nameservers
  # nameserver-policy:
  #   'www.baidu.com': '114.114.114.114'
  #   '+.internal.crop.com': '10.0.0.1'

proxies:
  # Shadowsocks
  # Supported encryption methods:
  #   aes-128-gcm aes-192-gcm aes-256-gcm
  #   aes-128-cfb aes-192-cfb aes-256-cfb
  #   aes-128-ctr aes-192-ctr aes-256-ctr
  #   rc4-md5 chacha20-ietf xchacha20
  #   chacha20-ietf-poly1305 xchacha20-ietf-poly1305
  - name: "ss1"
    type: ss
    server: server
    port: 443
    cipher: chacha20-ietf-poly1305
    password: "password"
    # udp: true

  - name: "ss2"
    type: ss
    server: server
    port: 443
    cipher: chacha20-ietf-poly1305
    password: "password"
    plugin: obfs
    plugin-opts:
      mode: tls # or http
      # host: bing.com

  - name: "ss3"
    type: ss
    server: server
    port: 443
    cipher: chacha20-ietf-poly1305
    password: "password"
    plugin: v2ray-plugin
    plugin-opts:
      mode: websocket # QUIC is not currently supported
      # tls: true # wss
      # skip-cert-verify: true
      # host: bing.com
      # path: "/"
      # mux: true
      # headers:
      #   custom: value

  # vmess
  # Supported encryption methods:
  #  auto/aes-128-gcm/chacha20-poly1305/none
  - name: "vmess"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    # udp: true
    # tls: true
    # skip-cert-verify: true
    # servername: example.com # Prioritize over wss host
    # network: ws
    # ws-opts:
    #   path: /path
    #   headers:
    #     Host: v2ray.com
    #   max-early-data: 2048
    #   early-data-header-name: Sec-WebSocket-Protocol

  - name: "vmess-h2"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    network: h2
    tls: true
    h2-opts:
      host:
        - http.example.com
        - http-alt.example.com
      path: /

  - name: "vmess-http"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    # udp: true
    # network: http
    # http-opts:
    #   # method: "GET"
    #   # path:
    #   #   - '/'
    #   #   - '/video'
    #   # headers:
    #   #   Connection:
    #   #     - keep-alive

  - name: vmess-grpc
    server: server
    port: 443
    type: vmess
    uuid: uuid
    alterId: 32
    cipher: auto
    network: grpc
    tls: true
    servername: example.com
    # skip-cert-verify: true
    grpc-opts:
      grpc-service-name: "example"

  # socks5
  - name: "socks"
    type: socks5
    server: server
    port: 443
    # username: username
    # password: password
    # tls: true
    # skip-cert-verify: true
    # udp: true

  # http
  - name: "http"
    type: http
    server: server
    port: 443
    # username: username
    # password: password
    # tls: true # https
    # skip-cert-verify: true
    # sni: custom.com

  # Snell
  # Please note, there is no UDP support currently.
  - name: "snell"
    type: snell
    server: server
    port: 44046
    psk: yourpsk
    # version: 2
    # obfs-opts:
      # mode: http # or tls
      # host: bing.com

  # Trojan
  - name: "trojan"
    type: trojan
    server: server
    port: 443
    password: yourpsk
    # udp: true
    # sni: example.com # aka Server Name
    # alpn:
    #   - h2
    #   - http/1.1
    # skip-cert-verify: true

  - name: trojan-grpc
    server: server
    port: 443
    type: trojan
    password: "example"
    network: grpc
    sni: example.com
    # skip-cert-verify: true
    udp: true
    grpc-opts:
      grpc-service-name: "example"

  - name: trojan-ws
    server: server
    port: 443
    type: trojan
    password: "example"
    network: ws
    sni: example.com
    # skip-cert-verify: true
    udp: true
    # ws-opts:
      # path: /path
      # headers:
      #   Host: example.com

  # ShadowsocksR
  # Supported encryption methods: All stream encryption methods in SS
  # Supported obfuscation methods:
  #   plain http_simple http_post
  #   random_head tls1.2_ticket_auth tls1.2_ticket_fastauth
  # Supported protocols:
  #   origin auth_sha1_v4 auth_aes128_md5
  #   auth_aes128_sha1 auth_chain_a auth_chain_b
  - name: "ssr"
    type: ssr
    server: server
    port: 443
    cipher: chacha20-ietf
    password: "password"
    obfs: tls1.2_ticket_auth
    protocol: auth_sha1_v4
    # obfs-param: domain.tld
    # protocol-param: "#"
    # udp: true

proxy-groups:
  # Relay chain proxy nodes. Nodes should not contain relays. UDP is not supported.
  # Traffic node chain: clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet
  - name: "relay"
    type: relay
    proxies:
      - http
      - vmess
      - ss1
      - ss2

  # url-test selects which proxy to use by benchmarking speed against a specified URL.
  - name: "auto"
    type: url-test
    proxies:
      - ss1
      - ss2
      - vmess1
    # tolerance: 150
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  # fallback-auto selects available policy based on priority. Availability is tested by accessing a specified URL, like the automatic url-test group.
  - name: "fallback-auto"
    type: fallback
    proxies:
      - ss1
      - ss2
      - vmess1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  # Load Balancing: Requests to the same eTLD+1 will be dialed to the same proxy.
  - name: "load-balance"
    type: load-balance
    proxies:
      - ss1
      - ss2
      - vmess1
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    # strategy: consistent-hashing # or round-robin

  # 'select' manual selection, used to select a proxy or policy group
  # You can use RESTful API to switch proxies, it is recommended to switch in GUI.
  - name: Proxy
    type: select
    # disable-udp: true
    # filter: 'someregex'
    proxies:
      - ss1
      - ss2
      - vmess1
      - auto

  # Connect directly to another interface name or fwmark, also supports proxy
  - name: en1
    type: select
    interface-name: en1
    routing-mark: 6667
    proxies:
      - DIRECT

  - name: UseProvider
    type: select
    use:
      - provider1
    proxies:
      - Proxy
      - DIRECT

proxy-providers:
  provider1:
    type: http
    url: "url"
    interval: 3600
    path: ./provider1.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204
  test:
    type: file
    path: /test.yaml
    health-check:
      enable: true
      interval: 36000
      url: http://www.gstatic.com/generate_204

tunnels:
  # Single line configuration
  - tcp/udp,127.0.0.1:6553,114.114.114.114:53,proxy
  - tcp,127.0.0.1:6666,rds.mysql.com:3306,vpn
  # Full yaml configuration
  - network: [tcp, udp]
    address: 127.0.0.1:7777
    target: target.com
    proxy: proxy

rules:
  - DOMAIN-SUFFIX,google.com,auto
  - DOMAIN-KEYWORD,google,auto
  - DOMAIN,google.com,auto
  - DOMAIN-SUFFIX,ad.com,REJECT
  - SRC-IP-CIDR,192.168.1.201/32,DIRECT
  # Optional parameter "no-resolve" for IP rules (GEOIP, IP-CIDR, IP-CIDR6)
  - IP-CIDR,127.0.0.0/8,DIRECT
  - GEOIP,CN,DIRECT
  - DST-PORT,80,DIRECT
  - SRC-PORT,7777,DIRECT
  - RULE-SET,apple,REJECT # Only supported in Premium version
  - MATCH,auto
